site_name: Pinax Badges
pages:
- Home: index.md
- Usage: usage.md
- API:
    - Models: models.md
    - Signals: signals.md
    - Template Tags: templatetags.md
theme: readthedocs
markdown_extensions:
    - admonition
